name: harvest-terms
on:
  schedule:
    - cron: "0 18 * * *"   # GitHubはUTC。JST 03:00に実行
  workflow_dispatch: {}     # 手動実行ボタン

permissions:
  contents: write
  pull-requests: write
  issues: write            # ラベル作成のため

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests

      - name: Harvest from Wikipedia
        env:
          # ← カテゴリをまとめて指定（数字は不要）
          CATEGORIES: >-
            プログラミング言語,オペレーティングシステム,データベース,
            ソフトウェア,ハードウェア,情報セキュリティ,
            人工知能,クラウドコンピューティング,ウェブ技術,データサイエンス
          LIMIT: "20"      # まずは20語/日で安全運転（慣れたら上げてOK）
          LANG: "ja"
          SLEEP: "1.2"     # 429対策で少しゆっくり
        run: python scripts/harvest.py

      # PRタイトル/メッセージ用に日付を生成
      - name: Set date
        id: now
        run: echo "date=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "harvest: update words.json (${{ steps.now.outputs.date }})"
          title: "Auto-harvest: ${{ steps.now.outputs.date }}"
          body: |
            自動収集の更新です（UTC）。
            日付=${{ steps.now.outputs.date }}
            カテゴリ=${{ env.CATEGORIES }} / 上限=${{ env.LIMIT }}語
          branch: chore/auto-harvest
          delete-branch: true
          labels: auto, harvest
