name: harvest-terms
on:
  schedule:
    - cron: "0 18 * * *"   # GitHubはUTC。JST 03:00に自動実行
  workflow_dispatch: {}     # 手動実行ボタン

permissions:
  contents: write
  pull-requests: write
  issues: write            # ラベル作成のため

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests

      # 1) 本日の日付と曜日を計算（PRタイトル/ブランチ用）
      - name: Set date
        id: now
        run: echo "date=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      # 2) 日替わりカテゴリを決定（月=1 ... 日=7）
      - name: Plan categories
        id: plan
        shell: bash
        run: |
          dow=$(date -u +'%u')  # 1..7
          case "$dow" in
            1) cats="プログラミング言語,オペレーティングシステム" ;;
            2) cats="データベース,ソフトウェア" ;;
            3) cats="ハードウェア,情報セキュリティ" ;;
            4) cats="人工知能,クラウドコンピューティング" ;;
            5) cats="ウェブ技術,データサイエンス" ;;
            6) cats="プログラミング言語,データベース,情報セキュリティ" ;;   # 週末は多め
            7) cats="人工知能,クラウドコンピューティング,ウェブ技術" ;;
          esac
          echo "categories=$cats" >> $GITHUB_OUTPUT
          echo "Using categories: $cats"

      # 3) 収集を実行（429対策で少しゆっくり）
      - name: Harvest from Wikipedia
        env:
          CATEGORIES: ${{ steps.plan.outputs.categories }}
          LIMIT: "40"     # まずは40語/日。429が出たら30→20へ
          LANG: "ja"
          SLEEP: "1.2"
        run: python scripts/harvest.py

      # 4) Pull Request を作成（同日に複数回走っても枝番で分かれる）
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "harvest: update words.json (${{ steps.now.outputs.date }})"
          title: "Auto-harvest: ${{ steps.now.outputs.date }} (${{ steps.plan.outputs.categories }})"
          body: |
            自動収集の更新です（UTC）。
            日付=${{ steps.now.outputs.date }}
            カテゴリ=${{ steps.plan.outputs.categories }}
            上限=${{ env.LIMIT }}語
          branch: chore/auto-harvest-${{ steps.now.outputs.date }}-${{ github.run_number }}
          delete-branch: true
          labels: auto, harvest
